"""Layer 3: does `_unet_mask`'s largest-component rule pick the GUIDED pad?

`_unet_mask` keeps `argmax(area)` of the connected components -- it has no
idea where the user actually seated the pad, even though every caller has
`guide_region` in scope. `_flash_diff_mask`'s own lobe cut had exactly this
bug and got a guide seed in round 16 (a real 555px error); the U-Net path
never did.

Also checks the label provenance question: the U-Net was distilled from
`_segment_via_flash_diff` pseudo-labels generated by `build_dataset.py`,
which calls it WITHOUT a seed -- i.e. with the pre-round-16 frame-centre
seed. If the model inherited that bias its blobs should sit closer to the
frame centre than to the real guide centre.

Research-only, read-only imports of production.
"""
import os, sys, glob
import numpy as np, cv2

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'functions', 'processEnhanceAndScore'))
import sfm_pipeline  # noqa: E402

# Real still-space guide centre for front_only_v1, measured off a real
# capture in round 16 (the seed that fixed _isolate_thumb_lobe).
GUIDE_CX, GUIDE_CY = 0.63, 0.50

sess = sfm_pipeline._get_thumb_seg_session()
print('U-Net session:', 'loaded' if sess is not None else 'UNAVAILABLE')
SIZE = sfm_pipeline._THUMB_SEG_IMG_SIZE

def unet_probs(gray):
    small = cv2.resize(gray, (SIZE, SIZE)).astype(np.float32) / 255.0
    logits = sess.run(['logits'], {'input': small[None, None]})[0][0, 0]
    return 1.0 / (1.0 + np.exp(-logits))

def components(gray):
    m = (unet_probs(gray) > 0.5).astype(np.uint8) * 255
    m = cv2.resize(m, (gray.shape[1], gray.shape[0]), interpolation=cv2.INTER_NEAREST)
    m = cv2.morphologyEx(m, cv2.MORPH_CLOSE, np.ones((31, 31), np.uint8))
    m = cv2.morphologyEx(m, cv2.MORPH_OPEN, np.ones((21, 21), np.uint8))
    n, lab, stats, cents = cv2.connectedComponentsWithStats(m)
    return n, lab, stats, cents

rows = []
for p in sorted(glob.glob(os.path.join(HERE, 'results', 'cache', '*front_burst*.jpg'))
                + glob.glob(os.path.join(HERE, 'results', 'cache', '*front_focuszone*.jpg'))
                + glob.glob(os.path.join(HERE, 'results', 'cache', '*sweep_burst*amb.jpg'))):
    g = cv2.imread(p, cv2.IMREAD_GRAYSCALE)
    if g is None:
        continue
    h, w = g.shape
    n, lab, stats, cents = components(g)
    if n <= 1:
        print("  %-34s no components" % os.path.basename(p)[-34:]); continue
    areas = stats[1:, cv2.CC_STAT_AREA]
    big = 1 + int(np.argmax(areas))
    # component the guide centre falls inside, else nearest centroid
    gx, gy = GUIDE_CX * w, GUIDE_CY * h
    at = int(lab[int(min(h - 1, gy)), int(min(w - 1, gx))])
    if at == 0:
        d = [np.hypot(cents[i][0] - gx, cents[i][1] - gy) for i in range(1, n)]
        at = 1 + int(np.argmin(d))
        inside = False
    else:
        inside = True
    frac_big = areas[big - 1] / float(g.size)
    frac_at = stats[at, cv2.CC_STAT_AREA] / float(g.size)
    cb = cents[big]; ca = cents[at]
    rows.append((os.path.basename(p)[-30:], n - 1, big == at, frac_big, frac_at,
                 cb[0] / w, cb[1] / h, inside))
    print("  %-30s comps=%-2d same=%-5s  largest frac=%.3f @cx=%.3f cy=%.3f   guided frac=%.3f  guide-inside=%s"
          % (os.path.basename(p)[-30:], n - 1, big == at, frac_big,
             cb[0] / w, cb[1] / h, frac_at, inside))

if rows:
    same = sum(1 for r in rows if r[2])
    print("\n  largest == guided on %d/%d frames" % (same, len(rows)))
    cxs = [r[5] for r in rows]; cys = [r[6] for r in rows]
    print("  largest-component centroid: cx median %.3f  cy median %.3f"
          % (float(np.median(cxs)), float(np.median(cys))))
    print("  frame centre = 0.500/0.500   real guide centre = %.3f/%.3f" % (GUIDE_CX, GUIDE_CY))
    print("  |cx - 0.500| = %.3f   |cx - %.2f| = %.3f"
          % (abs(np.median(cxs) - 0.5), GUIDE_CX, abs(np.median(cxs) - GUIDE_CX)))
    print("  mean largest-component area fraction of frame: %.3f"
          % float(np.mean([r[3] for r in rows])))
