// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  // appId updated 2026-08-15: this used to point at a DIFFERENT
  // registered Android app (com.clearbridge.app's -- ad3f7991...),
  // borrowed because this app's own real package, com.clearbridge.beta,
  // had never been registered in the Firebase project. That's fine for
  // Dart-only SDKs (Auth/Firestore/Storage/Functions, which don't
  // enforce package-name matching against FirebaseOptions), but real
  // crash reporting needs the app's own genuine registration --
  // registered via the Firebase Management API (real service-account
  // credentials, an additive action that didn't touch the other two
  // existing app registrations), now pointing at the correct app.
  // apiKey is unchanged -- confirmed identical across all three
  // registered apps in this project (one shared project-level key).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAus1IsVAvF0Z_LUBQO5pK6C9VKtCb3tEU',
    appId: '1:427514831103:android:bc34b32903b6a9dd48acca',
    messagingSenderId: '427514831103',
    projectId: 'clearbridge-dc699',
    storageBucket: 'clearbridge-dc699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1234567890abcdefghijklmnopqr',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'clearbridge-dc699',
    storageBucket: 'clearbridge-dc699.appspot.com',
    databaseURL: 'https://clearbridge-dc699.firebaseio.com',
    iosBundleId: 'com.clearbridge.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1234567890abcdefghijklmnopqr',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'clearbridge-dc699',
    storageBucket: 'clearbridge-dc699.appspot.com',
    databaseURL: 'https://clearbridge-dc699.firebaseio.com',
    authDomain: 'clearbridge-dc699.firebaseapp.com',
  );
}
