// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAus1IsVAvF0Z_LUBQO5pK6C9VKtCb3tEU',
    appId: '1:427514831103:android:ad3f79916c25252848acca',
    messagingSenderId: '427514831103',
    projectId: 'clearbridge-dc699',
    storageBucket: 'clearbridge-dc699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1234567890abcdefghijklmnopqr',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'clearbridge-dc699',
    storageBucket: 'clearbridge-dc699.appspot.com',
    databaseURL: 'https://clearbridge-dc699.firebaseio.com',
    iosBundleId: 'com.clearbridge.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1234567890abcdefghijklmnopqr',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'clearbridge-dc699',
    storageBucket: 'clearbridge-dc699.appspot.com',
    databaseURL: 'https://clearbridge-dc699.firebaseio.com',
    authDomain: 'clearbridge-dc699.firebaseapp.com',
  );
}
